# Generated by Django 3.0.2 on 2020-02-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='offer',
        ),
        migrations.AddField(
            model_name='package',
            name='discount',
            field=models.IntegerField(default="300"),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
