# Generated by Django 3.0.2 on 2020-02-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200225_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='discount',
            new_name='offer',
        ),
    ]
