# Generated by Django 3.0.2 on 2020-02-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200225_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.IntegerField(),
        ),
    ]
