# Generated by Django 3.0.2 on 2020-02-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200225_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='originalPrice',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
