# Generated by Django 3.0.2 on 2020-02-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200225_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='originalPrice',
            field=models.IntegerField(),
        ),
    ]
