# Generated by Django 3.0.2 on 2020-02-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='country',
            new_name='city',
        ),
    ]
