# Generated by Django 3.0.2 on 2020-02-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200225_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='totalPrice',
            field=models.CharField(default='', max_length=100),
        ),
    ]
