# Generated by Django 3.0.2 on 2020-02-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_orders_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='totalPrice',
            field=models.CharField(max_length=100),
        ),
    ]
