# Generated by Django 3.0.2 on 2020-02-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='images',
            field=models.ImageField(default='true', upload_to='blog/pics'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='chead0',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='chead1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='chead2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='pics'),
        ),
    ]
