# Generated by Django 3.0.2 on 2020-02-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200220_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='chead1',
            field=models.TextField(blank='True'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='chead2',
            field=models.TextField(blank='True'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head1',
            field=models.CharField(blank='True', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head2',
            field=models.CharField(blank='True', max_length=500),
        ),
    ]
